Add and use server package
grafana/influx2cortex pull request #41
Opened 2022-04-04 19:46 UTC by carrieedwards

This PR adds and uses a server package to handle the requests.

2022-04-05 18:42 UTC, ywwg requested changes
mostly some cleanup we need to do

2022-04-05 18:42 UTC, ywwg commented on pkg/route/registerer.go
> +// differs depending on if the proxy is running in Cloud or GEM.
remove reference to products

2022-04-05 18:42 UTC, ywwg commented on pkg/route/registerer.go
> +// FuncRegisterer allows a registerer to be defined by passing in functions. This is used for proxies in GEM.
same

2022-04-05 18:42 UTC, ywwg commented on pkg/server/middleware/logging.go
> +		// https://github.com/grafana/deployment_tools/blob/master/docs/infrastructure/tracing.md#special-tags
remove internal reference

2022-04-05 18:42 UTC, ywwg commented on pkg/server/middleware/logging_test.go
> +		req, err := http.NewRequest(http.MethodGet, fmt.Sprintf("https://grafana.net%s?api_key=%s", path, secretAPIKey), http.NoBody)
use dummy domain name instead

2022-04-05 18:42 UTC, ywwg commented on pkg/server/middleware/logging_test.go
> +		req, err := http.NewRequest(http.MethodGet, fmt.Sprintf("https://grafana.net%s?api_key=%s", path, grafanaLabsAPIKey), http.NoBody)
and elsewhere

2022-04-05 18:42 UTC, ywwg commented on pkg/server/server_test.go
> +	cfg.HTTPListenPort = 9097 // Override to avoid conflicting with other ports
can we use a port 0 method here to avoid multi-run issues?

2022-04-05 18:42 UTC, ywwg commented on pkg/util/bytereplacer/byte_replacer_test.go
> +// pkg: github.com/grafana/transmog/pkg/util/bytereplacer
remove internal reference

2022-04-05 20:41 UTC, ywwg commented
lint report has some items

2022-04-05 20:45 UTC, ywwg approved these changes
very nice!  Just one minor nit

2022-04-05 20:45 UTC, ywwg commented on pkg/influx/api.go
> +	level.Debug(a.logger).Log("msg", "successful series write", "len", len(rwReq.Timeseries))
this is going to be a very noisy line, I think we should only record the metric and not also print

2022-04-05 20:49 UTC, carrieedwards commented
For the linting report, is it necessary to check the error value of the logger?

2022-04-05 21:13 UTC, leizor commented
> For the linting report, is it necessary to check the error value of the logger?

I've been prepending those lines with `_ = ` (basically throwing away the result still, but doing it explicitly so the linter is happy).

2022-04-05 21:22 UTC, ywwg commented
I wonder if we can tweak the linter to ignore log return values specifically without having to do either this or a //nolint comment?  This is annoying to have to do.  There's an exhausting discussion here: https://github.com/go-kit/kit/issues/164

2022-04-05 21:23 UTC, ywwg commented
"""
If, when using Go kit, you want to ensure all logging errors are handled in some way then I believe the correct approach is to write a Logger decorator that handles errors returned by a wrapped logger as desired.
"""

2022-04-05 21:27 UTC, ywwg commented
so it seems that we should create an adapter layer that deals with (ignores) the errors so we don't have to hack the call site to satisfy the linter.  Example: https://github.com/go-kit/kit/issues/164#issuecomment-276304495

2022-04-06 15:25 UTC, carrieedwards commented
Should I try to fix the linting in a separate PR?

2022-04-06 15:52 UTC, ywwg approved these changes
thanks! good work importing this raft of packages

2022-04-06 15:53 UTC, merged